#- hosts: slave
#  tasks:
#  - name: Install package
#    yum:
#      name: git
#      state: present
---
- hosts: slave
  vars:
     contents: "{{ lookup('file', '/root/indata') }}"
  tasks:
     - command: yum install {{ contents  }} -y
